version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: dota-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dotadb
    ports:
      - "5432:5432"